# Generated by Django 5.1 on 2024-08-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogProf', '0003_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guilherme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='Guilherme')),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogProf.curso')),
            ],
        ),
        migrations.DeleteModel(
            name='Eu',
        ),
    ]
