# Generated by Django 5.1 on 2024-08-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogProf', '0006_rename_atividades_extra_atividades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoal',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
