# Generated by Django 5.1 on 2024-08-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogProf', '0008_pessoal_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoal',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
